
package com.epam.lab.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorSoapServiceImpl", targetNamespace = "http://soap.service.lab.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorSoapServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.AddResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/addRequest", output = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/addResponse")
    public String add(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "divide", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.DivideResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/divideRequest", output = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/divideResponse")
    public String divide(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.SubtractResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/subtractRequest", output = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/subtractResponse")
    public String subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "percentage", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Percentage")
    @ResponseWrapper(localName = "percentageResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.PercentageResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/percentageRequest", output = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/percentageResponse")
    public String percentage(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.MultiplyResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/multiplyRequest", output = "http://soap.service.lab.epam.com/CalculatorSoapServiceImpl/multiplyResponse")
    public String multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
