
package com.epam.lab.service.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorSoapServiceImplService", targetNamespace = "http://soap.service.lab.epam.com/", wsdlLocation = "http://localhost:8090/calc?wsdl")
public class CalculatorSoapServiceImplService
    extends Service
{

    private final static URL CALCULATORSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORSOAPSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATORSOAPSERVICEIMPLSERVICE_QNAME = new QName("http://soap.service.lab.epam.com/", "CalculatorSoapServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/calc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORSOAPSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATORSOAPSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CalculatorSoapServiceImplService() {
        super(__getWsdlLocation(), CALCULATORSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public CalculatorSoapServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculatorSoapServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORSOAPSERVICEIMPLSERVICE_QNAME);
    }

    public CalculatorSoapServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORSOAPSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculatorSoapServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorSoapServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorSoapServiceImpl
     */
    @WebEndpoint(name = "CalculatorSoapServiceImplPort")
    public CalculatorSoapServiceImpl getCalculatorSoapServiceImplPort() {
        return super.getPort(new QName("http://soap.service.lab.epam.com/", "CalculatorSoapServiceImplPort"), CalculatorSoapServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorSoapServiceImpl
     */
    @WebEndpoint(name = "CalculatorSoapServiceImplPort")
    public CalculatorSoapServiceImpl getCalculatorSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.lab.epam.com/", "CalculatorSoapServiceImplPort"), CalculatorSoapServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORSOAPSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATORSOAPSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CALCULATORSOAPSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
